<a href="https://colab.research.google.com/github/hwayoung306/AI/blob/main/20220412_py_04_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 구글드라이브 연동



In [1]:
# 구글드라이브 연동
from google.colab import drive
drive.mount('/gdrive', force_remount=True)

# 구글 드라이브 파일 확인
!ls '/gdrive/My Drive/temp/'

# 반복되는 드라이브 경로 변수화
drive_path = '/gdrive/My Drive/temp/'

Mounted at /gdrive
 매수종목1.txt			        sample.docx
'2. 영화평점, 날짜별 영화평점 시각화'   sample_merge.pdf
 매수종목2.txt			        sample.xlsx
 auto-mpg.csv			        score.csv
 bmi_500.csv			        seoul.html
 매수종목.csv			       'stock price (1).xlsx'
 data_studentlist_en.csv	       'stock price.xlsx'
'demo (1).docx'			        stock_px.csv
 demo.docx			       'stock valuation.xlsx'
 example.docx			        test.db.db
 height_weight.txt		        test.txt
 hello_world.xlsx		        Titanic배포용
 HelloWorld.xlsx		        titanic_test.csv
'little-char (1).png'		        titanic_train.csv
 little-char.png		        titanic.xls
 population_number.csv		        Traffic_Accident_2017.csv
 ram_price.csv			        train.csv
 ratings_small.txt		        user_id_mean.csv
'sample1 (1).pdf'		        wine.csv
 sample1.pdf			        주가데이터.xlsx
'sample (1).xlsx'		        남북한발전전력량.xlsx
 sample2.pdf


### 파이썬 머신러닝을 위한 모듈(라이브러리)


* 머신러닝 라이브러리
 * 사이킷런(Scikit-Learn)
* 행렬/선형대수/통계 라이브러리
  * **넘파이(NumPy): 고성능 과학계산을 위한 데이터 분석**(행렬, 선형대수)
  * 사이파이(SciPy): 자연과학, 통계
* 데이터 핸들링
 * 판다스(Pandas): 행과 열로 구성된 표 형식의 데이터(2차원 데이터 처리)
* 시각화
 * 맷플롯립(Matplotlib): 2D 그래프로 시각화
 * 시본(Seaborn): 다양한 색상 테마로 시각화

# Numpy (Numerical Python)
- 벡터 및 행렬 연산에 있어서 매우 편리한 기능을 제공
- 빠르고 효율적인 벡터 산술연산을 제공하는 n 차원 배열 (ndarray)
- 반복문 없이 전체 데이터 배열 연산이 가능한 표준 수학 함수 (sum(), sqrt(), mean())
- 선형대수, 난수 생성, 푸리에 변환

## Numpy 기초


In [2]:
# Numpy 모듈(라이브러리)를 import하고 np 라는 이름으로 부르는 것이 관례
import numpy as np

In [ ]:
np.__version__

numpy.ndarray

- 동일한 자료형을 가지는 값들이 배열 형태로 존재함
- N 차원 형태로 구성이 가능하다.
- 각 값들은 양의 정수로 색인(index)가 부여되어 있다.
- Numpy에서 차원(Dimension)을 rank, axis라고 부르기도 한다.
- ndarray를 줄여서 array로 표현한다.
- ndarray -> 차원이 있는 array


In [ ]:
list1 = [1,2,3]
array1 = np.array(list1)
print(type(array1))
print( array1.shape) # 배열의 크기 확인

array2 = np.array( [[1,2,3],
                  [4,5,6]])

print( type(array2))
print( array2.shape)

array3 = np.array([[1,2,3]])
print( type(array3))
print( array3.shape)

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)
<class 'numpy.ndarray'>
(1, 3)


In [ ]:
# Numpy 배열과 파이썬 리스트 성능 비교
# 백만개의 정수를 저장
import numpy as np
arr1 = np.arange(1000000)
list1 = list(range(1000000))

%time for _ in range(10) : arr2 = arr1 * 2
%time for _ in range(10) : list2 = [x*2 for x in list1]

CPU times: user 14.8 ms, sys: 4.24 ms, total: 19.1 ms
Wall time: 23.3 ms
CPU times: user 758 ms, sys: 204 ms, total: 962 ms
Wall time: 962 ms


ndarray.shape

해당 array의 크기를 알 수 있다.

- ndarray의 차원과 크기를 튜플(tuple) 형태로 출력

- shape 을 확인함으로써 몇 개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인할 수 있다.

- 위에서 array1.shape의 결과는 (3,) 으로써, 1차원의 데이터이며 총 3라는 크기를 갖고 있음을 알 수 있다.

- array2.shape의 결과는 (2,3) 으로써, 2차원의 데이터이며 2 * 3 크기를 갖고 있는 array 이다.


In [ ]:
# array 차원 확인
array1.ndim, array2.ndim, array3.ndim

(1, 2, 2)

In [ ]:
# array의 전체 요소 개수 확인
array1.size, array2.size, array3.size

(3, 6, 3)

numpy에서 사용되는 자료형

- 부호가 있는 정수 int(8, 16, 32, 64)
- 부호가 없는 정수 uint(8 ,16, 32, 54)
- 실수 float(16, 32, 64, 128)
- 복소수 complex(64, 128, 256)
- 불리언 bool
- 문자열 string_ -> 파이썬 내부에서 쓰는 코드
- 파이썬 오프젝트 object
- 유니코드 unicode_ -> 세계적으로  통용되는 체계


In [ ]:
list1 = [1,2,3]
array1 = np.array(list1)
print(type(array1))
print(array1)
print(array1.dtype)

<class 'numpy.ndarray'>
[1 2 3]
int64


In [ ]:
# 서로 다른 데이터 타입을 갖는 리스트일 때
list2 = [1,2, 'test']
print('list2', type(list2))

array2 = np.array(list2)
print('array2', array2.dtype, array2)

list3 = [1,2,3.1]
array3 = np.array(list3)
print('array3', array3.dtype, array3)

list2 <class 'list'>
array2 <U21 ['1' '2' 'test']
array3 float64 [1.  2.  3.1]


- 리스트와 다르게 ndarray는 같은 데이터 타입만 가능.
- 서로 다른 데이터 타입이 섞여 있을 경우 큰 데이터 타입으로 형 변환을 일괄 적용

In [ ]:
# 데이터 타입 변경하기(강제) .astype(변경할 타입)
array_int = np.array( [1,2,3] )
print( array_int, array_int.dtype )

array_float = array_int.astype('float64')
print( array_float, array_float.dtype )

array_int32 = array_int.astype(np.int32)
print( array_int32, array_int32.dtype )

array_float2 = np.array( [1.1, 2.2, 3.3 ] )
array_int2 = array_float2.astype('int32')
print( array_int2, array_int2.dtype )

[1 2 3] int64
[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [ ]:
arr = np.array([1.1,2.2,3.3], dtype=np.int32)
arr

array([1, 2, 3], dtype=int32)

#### Numpy 예제 01
Numpy를 이용해 다음과 같은 3차원 배열을 만들고 배열의 크기, 차원, 전체 요소 개수을 확인해보자 
```
array([[[1,2],
        [3,4]],
        
       [[5,6],
        [7,8]]])
```
```
배열의 모양: (2, 2, 2)
배열의 차원: 3
배열의 개수: 8
```


In [ ]:
array4 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(array4.shape)
print(array4.ndim)
print(array4.size)


(2, 2, 2)
3
8


### ndarray 생성

In [ ]:
# 연속 값으로 생성
seq_array = np.arange(10)
seq_array, seq_array.dtype, seq_array.shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int64'), (10,))

In [ ]:
# 초기화 0으로 채워진 배열 생성 zeros(크기, 데이터타입)
zero_array = np.zeros((3,2), dtype = 'int32')
zero_array, zero_array.dtype, zero_array.shape

(array([[0, 0],
        [0, 0],
        [0, 0]], dtype=int32), dtype('int32'), (3, 2))

In [ ]:
# 1로 초기화 시키기 ones(크기)
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# np.full( (행, 열), 넣을 데이터 값)
np.full( (5,5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
# 랜덤 값으로 초기화 
np.random.seed(10) # 시드 값이 있으면 매번 같은 랜덤 값이 들어감
np.random.rand(2,3) # 2행 3열 데이터 삽입

array([[0.75658709, 0.73002532, 0.17503925],
       [0.37531852, 0.06871881, 0.11886116]])

In [ ]:
# 랜덤 값의 범위 지정 
np.random.randint(2,10,size = (2,3)) # 숫자로 (2부터, 10까지, 크기는 2행 3열)

array([[2, 2, 7],
       [5, 7, 4]])

#### Numpy 예제 02
1,2,3,....,50 이 담긴 배열을 생성하시오.

In [ ]:
arr = np.arange(1,51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

### ndarray 차원과 크기 변경
- 차원 변경 되는 것이 있고 안되는 것도 있음

In [ ]:
# 내용의 사이즈 (크기)가 같아야 변환이 가능하다.
array1 = np.arange(10)
print(array1)

array2 = array1.reshape((2,5))
print(array2)

array3 = array1.reshape((5,2)) 
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# size가 동일? 하지 않음 - > 오류가 남
# array1은 10인데 9에 넣으려면 안들어가짐

# 오류남 : array1.reshape( (3,3) )

In [ ]:
# 자동변환 헹 열을 알수 없을 때 -1을 해주면 알아서 찾아줌

array1 = np.arange(10)
print(array1)

array2 = array1.reshape((2,-1))
print(array2)

array3 = array1.reshape((-1,2))
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# ndarray 형태 동일 (응용) -> list로 변환
array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
print(array3d.tolist())

# 차원 변경하기 크기가 같으면 차원 변경 가능 함
array5 = array3d.reshape(-1,1) # 8행 1열자리가 만들어짐
print(array5.tolist(), array5.shape)

array6 = array1.reshape(-1,1)
print(array6.tolist(), array6.shape)

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[0], [1], [2], [3], [4], [5], [6], [7]] (8, 1)
[[0], [1], [2], [3], [4], [5], [6], [7]] (8, 1)


### ndarray 인덱싱 & 슬라이싱
- 특정 데이터 추출
- 슬라이싱(Slicing) : 연속된 데이터 추출
- 팬시 인덱싱(Fancy Indexing) : 리스트 또는 ndarray 형태의 인덱싱 집합을 이용하여 여러 데이터를 추출
- 불린 인덱싱(Boolean Indexing) : True/False 값 인덱싱 집합을 이용하여 해당 인덱스 위치에 있는 데이터를 추출

In [ ]:
array7 = np.arange(1,10)
print(array7)

v = array7[2]
print(v, type(v))

[1 2 3 4 5 6 7 8 9]
3 <class 'numpy.int64'>


In [ ]:
# 9 8 4 1
array7[-1], array7[-2], array7[3], array7[0]

(9, 8, 4, 1)

In [ ]:
# 인덱스를 이용한 데이터 수정
array7[0] = 9
array7[8] = 0
array7

array([9, 2, 3, 4, 5, 6, 7, 8, 0])

In [ ]:
array7[0], array7[8] = array7[8], array7[0]

In [ ]:
array = np.arange(1, 7).reshape(2, 3)

display( array )
print(array[0])
print(array[0][0])
print(array[0,0])

array([[1, 2, 3],
       [4, 5, 6]])

[1 2 3]
1
1


In [4]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3,3)

print(array2d)
print('row=0', 'col=0', array2d[0,0])
print('row=0', 'col=1', array2d[0,1])
print('row=1', 'col=0', array2d[1,0])
print('row=2', 'col=2', array2d[2,2])
print('row=2', 'col=1', array2d[2,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
row=0 col=0 1
row=0 col=1 2
row=1 col=0 4
row=2 col=2 9
row=2 col=1 8


슬라이싱
- ':' 기호 앞에 시작 인덱스를 생략하면 맨 처음 인덱스인 0으로 간주
- ':' 기호 뒤에 종료 인덱스를 생략하면 맨 마지막 인덱스로 간주
- ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 맨 처음/마지막 인덱스로 간주



In [ ]:
# 1차원 슬라이싱
arr = np.arange(1, 10)
print(arr)
print(arr[0:3])
print(arr[:3])
print(arr[3:])
print(arr[:])

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# 2차원 슬라이싱
array = np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# array[행,열]
print(array[0:2,0:2])

[[1 2]
 [4 5]]


In [ ]:
array[1:3,0:3]
array[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
array[1:,1:2]

array([[5],
       [8]])

In [ ]:
array[:,:]

팬시 인덱싱 : 리스트 또는 ndarray 형태의 인덱싱 집합을 이용하여 여러 데이터를 추출

In [5]:
# 어떤 조건에 따라서 바꾸고 싶을 때 사용
# 1차원
arr = np.arange(1,10)
print( arr )
pindex = [2,4,7]
arr[ pindex ]

[1 2 3 4 5 6 7 8 9]


array([3, 5, 8])

In [7]:
# 2차원
arr = np.arange(1,10).reshape(3,3)
print(arr) ; print()

# 행 : 팬시인덱싱, 열 : 슬라이싱 인덱싱 
# arr[ [0,2], 2 ] : 행이 0행이고 2행인 값 중에서 2번째 열에 있는 값
print( arr[ [0,2], 2] )  ; print() # [3, 9] 
print( arr[ [0,2], 0:2 ] ) ; print() # [[1,2], [7,8]]
print( arr[ [0,2] ] ) ; print()# [[1, 2, 3],[7,8,9]]
print( arr[ [0,2], :] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[3 9]

[[1 2]
 [7 8]]

[[1 2 3]
 [7 8 9]]

[[1 2 3]
 [7 8 9]]


불린 인덱싱 : True/False 값 인덱싱 집합을 이용하여 해당 인덱스 위치에 있는 데이터를 추출

In [8]:
# 1차원
# 필터링과 검색이 동시에 가능하다
arr = np.arange(1,10)
print( arr )
print(arr>5)
bool_index = arr > 5
print(bool_index)
print(arr[bool_index]) # True인 부분만 나온다
arr[ arr > 5] # ndarray에 조건식 대입

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
[False False False False False  True  True  True  True]
[6 7 8 9]


array([6, 7, 8, 9])

In [ ]:
# 불린 인덱싱으로 필터링을 가능하게 함
bool_index = [False,True, False,False,False,True,True,True,True]
arr[bool_index]

array([2, 6, 7, 8, 9])

In [ ]:
# 불린 인덱싱 응용
names = np.array(['홍길동', '박철수', '이영희', '김영원', '변사또'])
scores = np.array([[60,60],[70,70],[80,80],[90,90],[100,100]])

names.shape, scores.shape

((5,), (5, 2))

In [ ]:
print(names == '홍길동')
scores[names == '홍길동']

[ True False False False False]


array([[60, 60]])

#### Numpy 예제 03 

BMI 구하기

10명에 대한 키와 몸무게가 들어있는 파일 ‘height_weight.txt’을 읽어 각 사람별 BMI 지수를 구하시오.
```
data = np.loadtxt(drive_path + "height_weight.txt", delimiter = ",") # delimiter : 구분자
data
```
  \\( BMI지수=\frac { 몸무게(kg) }{ 키(m) \times 키(m) } \\)
```
# 제곱 계산
# **2 or np.square()
```

In [ ]:
# 가져올 텍스트의 위치, 데이터들을 구분하는 요소(,나 공백, 텝 등)
data = np.loadtxt(drive_path + 'height_weight.txt', delimiter=",")
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [ ]:
data_array = data[1]/(data[0] / 100)**2
data_array

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

In [ ]:
bmi = []
for i in range(10) :
    bmi.append(data[1,0] / (data[0,i] / 100)**2)
bmi

[21.371531035633122,
 20.179592218429313,
 21.420408163265304,
 22.914116772574598,
 19.12589973363686,
 18.560434585785423,
 20.797824851878904,
 20.658007938217445,
 20.93906604104823,
 20.473767984769513]

In [ ]:
bmi = [ data[1, i] / (data[0, i] / 100)**2  for i in range(10) ]
bmi

In [ ]:
height = data[0] / 100
weight = data[1]

bmi = weight / height**2
bmi

### 행렬의 정렬
- sort() : 정렬
- argsort() : 정렬된 행렬의 원본 행렬 원소에 대한 인덱스를 반환

In [13]:
org_array = np.array([3,1,8,5])
sort_array = np.sort(org_array) # 원본이 바뀌지 않음
print( org_array )
print( sort_array )

[3 1 8 5]
[1 3 5 8]


In [15]:
sort_array = org_array.sort() # 원본을 바꿈

In [16]:
print( org_array)
print( sort_array) # 원본이 바뀌어서 사라짐

[1 3 5 8]
None


In [ ]:
org_array[::-1] # 전부를 거꾸로 출력하기

array([8, 5, 3, 1])

In [ ]:
# 내림차순
org_array = np.array([3,1,8,5])
np.sort(org_array)[::-1]

array([8, 5, 3, 1])

In [ ]:
# 2차원 정렬
array = np.array([[8,12],
                  [7,1]])
np.sort(array, axis =0)

array([[ 7,  1],
       [ 8, 12]])

In [ ]:
np.sort(array, axis = 1)

array([[ 8, 12],
       [ 1,  7]])

In [ ]:
# argsort : 원래 행렬의 값을 정렬이 된다면~ 몇번째 인덱스일꺼야!를 반환 (정렬된 행렬의 인덱스를 반환)
org_array = np.array([3,1,8,5])
sort_index = np.argsort( org_array )
sort_index

array([1, 0, 3, 2])

In [ ]:
org_array[ sort_index ] # 정렬이 된다면~ 몇번째 인덱스 일꺼야~를 팬시인덱스처럼 넣으면 정렬된 형태로 나옴

array([1, 3, 5, 8])

In [ ]:
# argsort 활용 - 팬시 인덱스로 적용
names = np.array(['홍길동', '박철수', '이영희', '김영원', '변사또'])
scores = np.array([78, 95, 84, 98, 88])

sort_index_asc = np.argsort(scores)
names[sort_index_asc][::-1]

array(['김영원', '박철수', '변사또', '이영희', '홍길동'], dtype='<U3')

### ndarray 연산
- 일반연산 : 산술연산, 비교연산 ... -> 요소 전부에 적용됨
- 선형대수 연산 : 행렬 내적과 전치 행렬

In [ ]:
array = np.array([1,2,3])
array + 100

array([101, 102, 103])

In [ ]:
array * 100

array([100, 200, 300])

In [ ]:
# [1,2,3]  1*1, 2*2, 3*3
array * array

array([1, 4, 9])

In [ ]:
# 행열끼리 연산을 하면 행끼리 연산을 함
array - array

array([0, 0, 0])

In [ ]:
array == 1

array([ True, False, False])

In [ ]:
# 행렬과 행렬의 비교는 인덱스가 같은 것 끼리 비교함
array == array

array([ True,  True,  True])

In [ ]:
array > array

array([False, False, False])

In [ ]:
# array*array 요소의 합 - 1차원일 때
np.dot(array, array)

14

In [ ]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7, 13).reshape(3,2)

print(a)
print()
print(b)
print()
print(np.dot(a,b))

[[1 2 3]
 [4 5 6]]

[[ 7  8]
 [ 9 10]
 [11 12]]

[[ 58  64]
 [139 154]]


In [ ]:
# 전치 행렬 : 가로 세로를 바꿔서
# 행과 열의 위치를 교환한 행렬
a = np.arange(1,7).reshape(2,3)

print( a )
print()
mat = np.transpose(a)
print(mat) # transpose로 가로 세로 바꾼것
a.T # T로 원래것을 가로 세로 바꾼것

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

### Universal 함수
- sin(), cos()다양한 수학함수를 제공
- 스칼라값을 입력으로 하는 math 패키지와 달리 배열에 대해 요소별로 적용

In [ ]:
# 합계를 구하는 방법 -> 요소 전부 더하기
array = np.arange(1,11)
array.sum()

55

In [ ]:
# 평균을 구하는 방법 -> 요소의 평균
array.mean()

5.5

In [ ]:
# 표준편차 -> 요소들의 표준편차
array.std()

2.8722813232690143

In [ ]:
# 음수를 양수로 바꾸어주는 !!
array = np.array([-1, -2, 3, 4, -5])
np.abs(array)

array([1, 2, 3, 4, 5])

In [ ]:
# 제곱근 -> 요소들 각각의 제곱근 구해서
array = np.arange(5)
np.sqrt( array )

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

#### Numpy 예제 04

영화평점 데이터 분석

In [ ]:
data = np.loadtxt(drive_path + 'ratings_small.txt', delimiter = '::', dtype = np.int64)
data.dtype

dtype('int64')

In [ ]:
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     1779,      2502,         4, 998699749],
       [     1779,      3160,         5, 977032398],
       [     1779,      3168,         4, 977033232]])

##### 데이터 분석하기
```
print(data.ndim) -> 차원
print(data.shape) -> 모양 (행, 열)
print(data.size) -> 데이터 개수
```

In [ ]:
# 행 (평점 작성 갯수) 300001개, 열 (데이터의 종류) 4개
# 300001 * 4 = 1200004
print(data.ndim) 
print(data.shape)
print(data.size) 

2
(300001, 4)
1200004


##### 전체 평점 평균 구하기
1. 평점 데이터만 추출 (인덱싱, 슬라이싱)
2. 평균 구하기 (mean)

In [ ]:
# 전체 평점 평균
print(data[:,2].mean())

# 분해
rating_all = data[:, 2]
rating_all.mean()

print(np.mean(data[:,2]))

3.5613081289729034
3.5613081289729034


##### 각 사용자별 평점 평균 구하기
1번 사용자의 평균 평점 구하기
1. 1번 사용자의 데이터만 Boolean Indexing 추출
2. 1번 사용자의 데이터에서 평점만 추출 (인덱싱, 슬라이싱)
3. 평균 구하기

참고
```
# 중복된 성분을 제외한 array를 반환
np.unique( ndarray )
```

In [ ]:
data[:, 0]
user_id_all = np.unique(data[:, 0]) # 총 사용자에서 중복값 제거
user_id_all.shape # 총 사용자의 수

(1779,)

In [ ]:
# 1번 사용자의 데이터만 가져오는 방법 Boolean Indexing 추출

bool_index_id = data[:, 0] == 1
user_1 = data[bool_index_id]

In [ ]:
# 1번 사용자의 데이터에서 평점만 추출 (인덱싱, 슬라이싱)
# 1번 사용자의 평균 구하기
user_1[:, 2].mean()

4.188679245283019

In [ ]:
# 또는 1번 사용자의 평균 구하기 (축약표현)
data[ data[:,0] == 1 ][:,2].mean()

4.188679245283019

In [ ]:
# 각 사용자별 평점 평균
score_mean = []

for i in range(1779+1) :
    score_mean.append([i,data[ data[:,0] == i ][:,2].mean()])

score_mean

In [ ]:
scores = [ [i,data[ data[:,0] == i ][:,2].mean()] for i in user_id_all]
scores

##### 각 사용자 별 평균 평점이 4점 이상인 사용자 구하기
- 리스트는 Boolean Indexing이 안되니 배열로 변환해야 인덱싱, 슬라이싱 가능

In [ ]:
score = np.array( score_mean)

boolean_index = score[:, 1] >= 4
# print(score[ boolean_index ])
print(score[ boolean_index ]. shape)


(448, 2)


In [ ]:
score = np.array( score_mean )
boolean_index = score[:, 1] >= 4
user_rating_4 = score[ boolean_index ]
mat = user_rating_4[:,0].astype(np.int64)
mat.size

# 같은 방법
# score[ score[:,1] >= 4][:, 0].astype(np.int64)

###### 질문

평점 4점이 넘는 사용자만 구하려면,
user_rate_avg의 결과 값을 리스트로 모은 후 ndarray 형식으로 바꾸는 방법밖에 없나요?

In [ ]:
import pandas as pd

df = pd.DataFrame(data)
df_mean = df[ [0,2] ].groupby(0).mean()
df_mean[df_mean[2] >= 4]

2
0             
1     4.188679
4     4.190476
7     4.322581
10    4.114713
17    4.075829
...        ...
1744  4.064286
1746  4.404908
1751  4.428571
1764  4.091354
1771  4.333333

[448 rows x 1 columns]

##### CSV 파일로 저장
- np.savetxt() 이용

In [ ]:
# 저장위치+파일이름, 저장할 데이터, drlimiter(구분자) = "", fmt(포매팅)
np.savetxt(drive_path + 'user_id_mean.csv', 
           score_mean, delimiter=', ', fmt='%.3f')

## Numpy 요약

In [ ]:
import numpy as np

In [ ]:
# 리스트 * 3 을 하면 3번 반복이지만
ll = [1, 2, 10]
print (ll * 3)

# 각 요소에 3씩 곱해짐
arr = np.array( ll )
print(arr * 3) 

[1, 2, 10, 1, 2, 10, 1, 2, 10]
[ 3  6 30]


In [ ]:
x = np.array( [[8,4,11,5],
              [2,10,7,3],
              [9,12,1,6]] )

print(x)
print()
x.sort() # 기본 촉 값이 1 (행기준)
print(x)

[[ 8  4 11  5]
 [ 2 10  7  3]
 [ 9 12  1  6]]

[[ 4  5  8 11]
 [ 2  3  7 10]
 [ 1  6  9 12]]


In [ ]:
x = np.array( [[8,4,11,5],
              [2,10,7,3],
              [9,12,1,6]] )

print(x)
print()
x.sort(0) # 축을 0으로 바꿈 (열기준)
print(x)

[[ 8  4 11  5]
 [ 2 10  7  3]
 [ 9 12  1  6]]

[[ 2  4  1  3]
 [ 8 10  7  5]
 [ 9 12 11  6]]


In [ ]:
# 순서를 랜덤으로 배꾸는 방법
x = np.arange(10)
print(x)
z = np.random.permutation(x)
print(z)

[0 1 2 3 4 5 6 7 8 9]
[6 0 1 9 3 5 4 2 7 8]


### 배열의 차원 확장

array 1차원을 -> array 2차원으로 확장

In [ ]:
x = np.arange(10)
print(x)

# 배열 확장 extand
# 열로 확장 (세로)
arr1 = np.expand_dims(x, 1)
print( arr1.shape )
print( arr1 )

# 행으로 확장 (가로)
arr2 = np.expand_dims(x, 0)
print( arr2.shape )
print( arr2 )

[0 1 2 3 4 5 6 7 8 9]
(10, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(1, 10)
[[0 1 2 3 4 5 6 7 8 9]]


In [ ]:
arr3 = np.expand_dims(x, axis = (0,1)) # tuple을 축으로 사용할 수 있다.
arr3.shape

(1, 1, 10)

In [ ]:
print(arr)
arr[:, np.newaxis]

[[[0 1 2 3 4 5 6 7 8 9]]]


array([[[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]]])

기존 데이터에서 배열 생성

In [ ]:
# np.vstack(), np.hstack(), np.vsplit(). np.hsplit()
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)

print(arr1)
print()
print(arr2)
print()

# np.vstack(), np.hstack()
print( np.hstack( (arr1, arr2) ) ) # 가로
print()
print( np.vstack( (arr1, arr2) ) ) # 세로
print()

# np.vsplit(), np.hsplit
print( np.vsplit( arr1, 2 ))
print()
print( np.hsplit( arr1, 2 ))
print()

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[array([[1, 2]]), array([[3, 4]])]

[array([[1],
       [3]]), array([[2],
       [4]])]



In [ ]:
# 깊은 복사
arr3 = arr1.copy()
arr3

array([[1, 2],
       [3, 4]])