<a href="https://colab.research.google.com/github/hwayoung306/AI/blob/main/20220412_py_04_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 구글드라이브 연동



In [1]:
# 구글드라이브 연동
from google.colab import drive
drive.mount('/gdrive', force_remount=True)

# 구글 드라이브 파일 확인
!ls '/gdrive/My Drive/temp/'

# 반복되는 드라이브 경로 변수화
drive_path = '/gdrive/My Drive/temp/'

Mounted at /gdrive
demo.docx	  little-char.png  sample.docx
hello_world.xlsx  sample1.pdf	   sample.xlsx


### 파이썬 머신러닝을 위한 모듈(라이브러리)


* 머신러닝 라이브러리
 * 사이킷런(Scikit-Learn)
* 행렬/선형대수/통계 라이브러리
  * **넘파이(NumPy): 고성능 과학계산을 위한 데이터 분석**(행렬, 선형대수)
  * 사이파이(SciPy): 자연과학, 통계
* 데이터 핸들링
 * 판다스(Pandas): 행과 열로 구성된 표 형식의 데이터(2차원 데이터 처리)
* 시각화
 * 맷플롯립(Matplotlib): 2D 그래프로 시각화
 * 시본(Seaborn): 다양한 색상 테마로 시각화

# Numpy (Numerical Python)
- 벡터 및 행렬 연산에 있어서 매우 편리한 기능을 제공
- 빠르고 효율적인 벡터 산술연산을 제공하는 n 차원 배열 (ndarray)
- 반복문 없이 전체 데이터 배열 연산이 가능한 표준 수학 함수 (sum(), sqrt(), mean())
- 선형대수, 난수 생성, 푸리에 변환

## Numpy 기초


In [2]:
# Numpy 모듈(라이브러리)를 import하고 np 라는 이름으로 부르는 것이 관례
import numpy as np

In [ ]:
np.__version__

numpy.ndarray

- 동일한 자료형을 가지는 값들이 배열 형태로 존재함
- N 차원 형태로 구성이 가능하다.
- 각 값들은 양의 정수로 색인(index)가 부여되어 있다.
- Numpy에서 차원(Dimension)을 rank, axis라고 부르기도 한다.
- ndarray를 줄여서 array로 표현한다.
- ndarray -> 차원이 있는 array


In [27]:
list1 = [1,2,3]
array1 = np.array(list1)
print(type(array1))
print( array1.shape) # 배열의 크기 확인

array2 = np.array( [[1,2,3],
                  [4,5,6]])

print( type(array2))
print( array2.shape)

array3 = np.array([[1,2,3]])
print( type(array3))
print( array3.shape)

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)
<class 'numpy.ndarray'>
(1, 3)


In [8]:
# Numpy 배열과 파이썬 리스트 성능 비교
# 백만개의 정수를 저장
import numpy as np
arr1 = np.arange(1000000)
list1 = list(range(1000000))

%time for _ in range(10) : arr2 = arr1 * 2
%time for _ in range(10) : list2 = [x*2 for x in list1]

CPU times: user 23.8 ms, sys: 10.4 ms, total: 34.1 ms
Wall time: 33.8 ms
CPU times: user 791 ms, sys: 185 ms, total: 976 ms
Wall time: 980 ms


ndarray.shape

해당 array의 크기를 알 수 있다.

- ndarray의 차원과 크기를 튜플(tuple) 형태로 출력

- shape 을 확인함으로써 몇 개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인할 수 있다.

- 위에서 array1.shape의 결과는 (3,) 으로써, 1차원의 데이터이며 총 3라는 크기를 갖고 있음을 알 수 있다.

- array2.shape의 결과는 (2,3) 으로써, 2차원의 데이터이며 2 * 3 크기를 갖고 있는 array 이다.


In [28]:
# array 차원 확인
array1.ndim, array2.ndim, array3.ndim

(1, 2, 2)

In [29]:
# array의 전체 요소 개수 확인
array1.size, array2.size, array3.size

(3, 6, 3)

numpy에서 사용되는 자료형

- 부호가 있는 정수 int(8, 16, 32, 64)
- 부호가 없는 정수 uint(8 ,16, 32, 54)
- 실수 float(16, 32, 64, 128)
- 복소수 complex(64, 128, 256)
- 불리언 bool
- 문자열 string_
- 파이썬 오프젝트 object
- 유니코드 unicode_


In [10]:
list1 = [1,2,3]
array1 = np.array(list1)
print(type(array1))
print(array1)
print(array1.dtype)

<class 'numpy.ndarray'>
[1 2 3]
int64


In [13]:
# 서로 다른 데이터 타입을 갖는 리스트일 때
list2 = [1,2, 'test']
print('list2', type(list2))

array2 = np.array(list2)
print('array2', array2.dtype, array2)

list3 = [1,2,3.1]
array3 = np.array(list3)
print('array3', array3.dtype, array3)

list2 <class 'list'>
array2 <U21 ['1' '2' 'test']
array3 float64 [1.  2.  3.1]


- 리스트와 다르게 ndarray는 같은 데이터 타입만 가능.
- 서로 다른 데이터 타입이 섞여 있을 경우 큰 데이터 타입으로 형 변환을 일괄 적용

In [21]:
# 데이터 타입 변경하기(강제)
array_int = np.array( [1,2,3] )
print( array_int, array_int.dtype )

array_float = array_int.astype('float64')
print( array_float, array_float.dtype )

array_int32 = array_int.astype(np.int32)
print( array_int32, array_int32.dtype )

array_float2 = np.array( [1.1, 2.2, 3.3 ] )
array_int2 = array_float2.astype('int32')
print( array_int2, array_int2.dtype )

[1 2 3] int64
[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [24]:
arr = np.array([1.1,2.2,3.3], dtype=np.int32)
arr

array([1, 2, 3], dtype=int32)

#### Numpy 예제 01
Numpy를 이용해 다음과 같은 3차원 배열을 만들고 배열의 크기, 차원, 전체 요소 개수을 확인해보자 
```
array([[[1,2],
        [3,4]],
        
       [[5,6],
        [7,8]]])
```
```
배열의 크기: (2, 2, 2)
배열의 차원: 3
배열의 개수: 8
```


In [35]:
array4 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(array4.shape)
print(array4.ndim)
print(array4.size)


(2, 2, 2)
3
8


### ndarray 생성

In [36]:
# 연속 값으로 생성
seq_array = np.arange(10)
seq_array, seq_array.dtype, seq_array.shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int64'), (10,))

In [38]:
# 초기화 0으로 채워진 배열 생성
zero_array = np.zeros((3,2), dtype = 'int32')
zero_array, zero_array.dtype, zero_array.shape

(array([[0, 0],
        [0, 0],
        [0, 0]], dtype=int32), dtype('int32'), (3, 2))

In [40]:
# 1로 초기화 시키기
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
# np.full( (행, 열), 넣을 데이터 값)
np.full( (5,5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [44]:
# 랜덤 값으로 초기화 
np.random.seed(10) # 시드 값이 있으면 매번 같은 랜덤 값이 들어감
np.random.rand(2,3) # 2행 3열 데이터 삽입

array([[0.75658709, 0.73002532, 0.17503925],
       [0.37531852, 0.06871881, 0.11886116]])

In [46]:
# 랜덤 값의 범위 지정 
np.random.randint(2,10,size = (2,3)) # 숫자로 (2부터, 10까지, 크기는 2행 3열)

array([[2, 2, 7],
       [5, 7, 4]])

#### Numpy 예제 02
1,2,3,....,50 이 담긴 배열을 생성하시오.

In [48]:
np.arange(1,51)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

### ndarray 차원과 크기 변경
- 차원 변경 되는 것이 있고 안되는 것도 있음

In [51]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape((2,5))
print(array2)

array3 = array1.reshape((5,2)) 
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# size가 동일? 하지 않음 - > 오류가 남
# array1은 10인데 9에 넣으려면 안들어가짐

array1.reshape( (3,3) )

In [56]:
# 자동변환 헹 열을 알수 없을 때 -1을 해주면 알아서 찾아줌

array1 = np.arange(10)
print(array1)

array2 = array1.reshape((2,-1))
print(array2)

array3 = array1.reshape((-1,2))
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [65]:
# ndarray 형태 동일 -> list로 변환
array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
print(array3d.tolist())

# 차원 변경하기 크기가 같으면 차원 변경 가능 함
array5 = array3d.reshape(-1,1) # 8행 1열자리가 만들어짐
print(array5.tolist(), array5.shape)

array6 = array1.reshape(-1,1)
print(array6.tolist(), array6.shape)

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
[[0], [1], [2], [3], [4], [5], [6], [7]] (8, 1)
[[0], [1], [2], [3], [4], [5], [6], [7]] (8, 1)


### ndarray 인덱싱 & 슬라이싱
- 특정 데이터 추출
- 슬라이싱(Slicing) : 연속된 데이터 추출
- 팬시 인덱싱(Fancy Indexing) : 리스트 또는 ndarray 형태의 인덱싱 집합을 이용하여 여러 데이터를 추출
- 불린 인덱싱(Boolean Indexing) : True/False 값 인덱싱 집합을 이용하여 해당 인덱스 위치에 있는 데이터를 추출

In [80]:
array7 = np.arange(1,10)
print(array7)

v = array7[2]
print(v, type(v))

[1 2 3 4 5 6 7 8 9]
3 <class 'numpy.int64'>


In [69]:
# 9 8 4 1
array7[-1], array7[-2], array7[3], array7[0]

(9, 8, 4, 1)

In [ ]:
for i in array

In [83]:
# 인덱스를 이용한 데이터 수정
array7[0] = 9
array7[8] = 0
array7

array([9, 2, 3, 4, 5, 6, 7, 8, 0])

슬라이싱
- ':' 기호 앞에 시작 인덱스를 생략하면 맨 처음 인덱스인 0으로 간주
- ':' 기호 뒤에 종료 인덱스를 생략하면 맨 마지막 인덱스로 간주
- ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 맨 처음/마지막 인덱스로 간주



#### Numpy 예제 03 

BMI 구하기

10명에 대한 키와 몸무게가 들어있는 파일 ‘height_weight.txt’을 읽어 각 사람별 BMI 지수를 구하시오.
```
data = np.loadtxt(drive_path + "height_weight.txt", delimiter = ",") # delimiter : 구분자
data
```
  \\( BMI지수=\frac { 몸무게(kg) }{ 키(m) \times 키(m) } \\)
```
# 제곱 계산
# **2 or np.square()
```

### 행렬의 정렬
- sort() : 정렬
- argsort() : 정렬된 행렬의 원본 행렬 원소에 대한 인덱스를 반환

### ndarray 연산
- 일반연산 : 산술연산, 비교연산 ...
- 선형대수 연산 : 행렬 내적과 전치 행렬

### Universal 함수
- sin(), cos()다양한 수학함수를 제공
- 스칼라값을 입력으로 하는 math 패키지와 달리 배열에 대해 요소별로 적용

#### Numpy 예제 04

영화평점 데이터 분석

##### 데이터 분석하기
```
print(data.ndim)
print(data.shape)
print(data.size)
```

##### 전체 평점 평균 구하기
1. 평점 데이터만 추출 (인덱싱, 슬라이싱)
2. 평균 구하기 (mean)

##### 각 사용자별 평점 평균 구하기
1번 사용자의 평균 평점 구하기
1. 1번 사용자의 데이터만 Boolean Indexing 추출
2. 1번 사용자의 데이터에서 평점만 추출 (인덱싱, 슬라이싱)
3. 평균 구하기

참고
```
# 중복된 성분을 제외한 array를 반환
np.unique( ndarray )
```

##### 각 사용자 별 평균 평점이 4점 이상인 사용자 구하기
- 리스트는 Boolean Indexing이 안되니 배열로 변환해야 인덱싱, 슬라이싱 가능

###### 질문

평점 4점이 넘는 사용자만 구하려면,
user_rate_avg의 결과 값을 리스트로 모은 후 ndarray 형식으로 바꾸는 방법밖에 없나요?

##### CSV 파일로 저장
- np.savetxt() 이용

## Numpy 요약

In [ ]:
import numpy as np